# File: run_test.yaml
name: "run-robot-test"
inputs:
  test_suite:
    description: "test_suite"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Test
      run: |
        test_suite=${{ inputs.test_suite }}
        if [ "${test_suite}" == "daexim" ]; then
          robot_test_file="./010-special-export.robot 020-import-basic.robot 030-export-basic.robot 040-export-inclusions.robot"
        elif [ "${test_suite}" == "distribution" ]; then
          robot_test_file="karaf_sequence_install.robot karaf_stop.robot size.robot"
        elif [ "${test_suite}" == "aaa" ]; then
          robot_test_file="authn"
        fi
        docker exec robot bash -c "git clone https://github.com/opendaylight/integration-test.git &&
          cd integration-test/csit/suites/${test_suite} &&
          robot -L debug --variable USER_HOME:/root \
            --variable WORKSPACE:/home/user \
            -v BUNDLEFOLDER:karaf-0.18.1 \
            -v ODL_STREAM:argon \
            --variable DEFAULT_LINUX_PROMPT:\\\$ \
            --variable ODL_SYSTEM_USER:user \
            --variable ODL_SYSTEM_IP:opendaylight \
            --variable ODL_SYSTEM_1_IP:opendaylight \
            -v IS_KARAF_APPL:True \
            $robot_test_file"
      shell: bash
